import { NextResponse } from 'next/server';
import crypto from 'crypto';

const OTP_SECRET = process.env.OTP_SECRET || 'dbohrarishta_super_secret_otp_key_2026';
const FIREBASE_DETERMINISTIC_SALT = process.env.FIREBASE_DETERMINISTIC_SALT || 'dbohrarishta_firebase_salt_2026';

export async function POST(req: Request) {
    try {
        const { phone, otp, hash, expiry } = await req.json();

        if (!phone || !otp || !hash || !expiry) {
            return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
        }

        // 1. Check Expiry
        if (Date.now() > Number(expiry)) {
            return NextResponse.json({ error: 'OTP has expired. Please request a new one.' }, { status: 400 });
        }

        // 2. Validate Hash
        const data = `${phone}.${otp}.${expiry}`;
        const computedHash = crypto.createHmac('sha256', OTP_SECRET).update(data).digest('hex');

        if (computedHash !== hash) {
            return NextResponse.json({ error: 'Invalid OTP' }, { status: 400 });
        }

        // 3. Generate Deterministic Internal Firebase Credentials
        // This is a 100% free workaround to create a session in Firebase Auth
        // using Email/Password under the hood, perfectly syncing with Firestore Rules
        // without paying any Firebase Phone Verification fees!
        const cleanPhone = phone.replace(/[\s\-\+]/g, '');
        const internalEmail = `${cleanPhone}@dbohrarishta.local`;

        // Highly secure deterministic password only generated by the server side
        const internalPassword = crypto.createHmac('sha256', FIREBASE_DETERMINISTIC_SALT).update(cleanPhone).digest('hex').substring(0, 24);

        return NextResponse.json({
            success: true,
            internalEmail,
            internalPassword,
            message: "OTP Verified Successfully"
        });

    } catch (error: any) {
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
